[PHP]
engine = On
short_open_tag = Off
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
serialize_precision = -1
disable_functions =
disable_classes =
expose_php = Off
max_execution_time = 300
max_input_time = 300
max_input_vars = 3000
memory_limit = 256M
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = On
display_startup_errors = On
log_errors = On
error_log = /var/log/apache2/php_errors.log
post_max_size = 64M
default_charset = "ISO-8859-1"
file_uploads = On
upload_max_filesize = 32M
max_file_uploads = 20
date.timezone = America/Santiago
mbstring.language = neutral
mbstring.internal_encoding = UTF-8